---
title: "U.S. National Parks Travle Plan"
author: "Neal Yu"
date: "February 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(leaflet)
library(ggplot2)
library(tidyr)
library(dplyr)
library(RCurl)
```

## National Parks

```{r read and process data, include=FALSE}
df_raw <- read.csv(file = "https://raw.github.com/nealxun/DataProdcutProject_Leaflet/gh-pages/national_parks.csv", 
                   header = TRUE, stringsAsFactors = FALSE)

```

```{r maps, echo = FALSE, warning=FALSE, message=FALSE}
# parks icon
parkIcon <- makeIcon(iconUrl ="national-park-map-icons.png",
                     iconWidth = 31*215/230, iconHeight = 31,
                     iconAnchorX = 31*215/230/2, iconAnchorY = 16)
# park website link
parkSites <- paste0("<a href = '", df_raw$weblink, "'>", df_raw$name, "</a>")
# visited time
parkLabel <- df_raw$date
# latitude and longitude
df_park <- data.frame(latitude = df_raw$latitude, longitude = df_raw$longitude, 
                      col = df_raw$color, stringsAsFactors = FALSE)
df_park %>% 
        leaflet() %>%
        addTiles() %>%
        addCircleMarkers(clusterOptions = markerClusterOptions(), 
                         popup = parkSites, label = parkLabel, 
                         color = df_park$col) %>%
        addLegend(labels = unique(df_raw$note), col = unique(df_raw$color))
```
